apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-tzy4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kiiq-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-tzy4@sha256:e58577f2bdfd592596d6514af17659968a9c2876b238b43b571b160b26ab642d
        name: my-go
        resources: {}
status: {}
